### ISSUE TITLE
Store log messages

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton#123]
it has been suggested in https://github.com/metanorma/metanorma-standoc/issues/862 that we store the fetch messages and errors from Relaton in the Metanorma error log, so that users can go back and go through a saved version of the messages, rather than have to scroll though the screen to work out what has happened.

I agree it is a good idea for usability. But I also see that it will require some refactoring to realise.

I call Relaton as `@bibdb.fetch_async()`, where `@bibdb` of course is just the class `Relaton::Db`. The simplest thing to do I think is, create a `@log` attribute on `Relaton::Db`, to store log messages as an hash, from reference tag to log of messages. (That way, all messages group together, though they are generated asynchronously.) So:

When you do a `Util.warn` in the various flavour gems, Util.warn can append the error message to the `@log` on the parent `Relaton::Db` class. Then, I iterate through `@bibdb.log` after I've finished all fetches, and add its log entries to my log's entries, which I then save to disk. 

When a retrieval fails, I already indicate that in my log, because you return nil. But it would be useful to differentiate between info log messages and errors, by inserting a severity rating: 0 for error, 1 for info, say. So:

````
Class Db

@log = {}

...

module Util

(I can't work out how it works, sorry)

@db = (give access to the Relaton::Db class instance)

def log(message, key: "", severity: 1)
...
@db.log[key] ||= []
@db.log[key] << {severity: severity, msg: message}
end

...
module RelatonOmg
  module OmgBibliography
  class << self

  def get(code, _year = nil, _opts = {})
        Util.warn "(#{code}) Fetching from www.omg.org ...", key: code
        result = search code
        if result
          Util.warn "(#{code}) Found: `#{result.docidentifier.first.id}`", key: code
        else
          Util.warn "(#{code}) Not found.", key: code, severity: 0
        end
        result
      end
````

**Comment by andrew2net** [comment]
@opoudjis I think the `@log` varible can consume significant memory space. We shouldn't store all the log messages in the memory. Also `Relaton::Db` isn't available in flavor gems.

I suggest other approaches. Let me know what you think about them.

1.
Use JSON format for logging. For example each line in log will be looks like:
```
{ progname: "relaton-iso", key: "ISO 123", msg: "Found: `ISO 123:2001`", severity: 1 }
```
so each line can be parsed and analyzed.
Output log messages to file instead of stderr. All flavor gems' logging can be redirected to the file. You can read lines from the file and parse each line:
```ruby
log = File.open "log.txt"
until log.eof?
  msg_hash = JSON.parse log.gets
  # do whatether it needs with the log message
end
```
 After reading all the lines from the log file you can remove it, so next time the file will contain only new data. Or you can keep open the file to have last reading position.

2.
Create singleton storage calss for storing log messages in memory, so any relaton flavor gem can put messages to the storage. The memory storage should drop old messages when number of messages exceed a limit (for example 1000 lines). After reading a message is removed from the storage.
```ruby
until Relaton::LogStorage.instance.empy?
  msg_hash = Relaton::LogStorage.instance.pop
  # do whatether it needs with the log message
end
```

**Comment by opoudjis** [comment]
A clean solution would be one where there is a distinct log file for each Metanorma session across all its relaton calls, than one where there is a single log file for all calls with expiration. That  sounds more feasible under 1 than under 2. Can I initialise the log file instance as a tempfile from Metanorma, and pass it to my initialisation of relaton?

**Comment by andrew2net** [comment]
> Can I initialise the log file instance as a tempfile from Metanorma, and pass it to my initialisation of relaton?

You can't do it right now, but if it's what we need I can implement this behavior.

**Comment by opoudjis** [comment]
I'd prefer that, thank you!

**Comment by andrew2net** [comment]
Implemented logger gem https://github.com/relaton/relaton-logger#usage
Relaton updated to use the new logger in v1.19.0
